"use client";

import Link from "next/link";
import {
  ArrowRight,
  BarChart3,
  Boxes,
  Building2,
  Check,
  ChevronDown,
  Menu,
  ReceiptText,
  ShieldCheck,
  ShoppingCart,
  Truck,
  Users,
  WalletCards,
  X,
} from "lucide-react";
import { useState } from "react";

const features = [
  { icon: ShoppingCart, title: "Sell faster", text: "A focused POS for quick, accurate transactions at the counter." },
  { icon: Boxes, title: "Trust your stock", text: "See what is available, moving, or ready for a reorder." },
  { icon: Truck, title: "Control purchases", text: "Record goods received and keep supplier balances in view." },
  { icon: Users, title: "Know your customers", text: "Manage customer accounts, credit, and payment history." },
  { icon: Building2, title: "Grow across branches", text: "Keep locations, registers, teams, and stock connected." },
  { icon: BarChart3, title: "Read the numbers", text: "Turn daily activity into decisions you can act on." },
];

const plans = [
  { name: "Starter", label: "For small shops getting organised", features: ["Point of sale", "Products and inventory", "Customer and supplier records", "Essential sales reports"] },
  { name: "Growth", label: "For businesses ready to scale", popular: true, features: ["Everything in Starter", "Purchases and supplier payments", "Customer credit", "Stock transfers and advanced reports"] },
  { name: "Enterprise", label: "For multi-branch operations", features: ["Everything in Growth", "Multi-branch controls", "Advanced permissions", "Priority support and custom needs"] },
];

const faqs = [
  ["What is DukaOS?", "DukaOS is a POS and business management platform for sales, inventory, purchases, customers, suppliers, and operations in one secure workspace."],
  ["Can I manage multiple branches?", "Yes. DukaOS is built to keep multiple branches, registers, users, and stock connected as your business grows."],
  ["Does DukaOS manage customer credit?", "Yes. Record credit sales, track outstanding balances, and capture payments against customer accounts."],
  ["Do I need special hardware?", "DukaOS runs in a web browser on compatible computers and POS devices, so you can work with the equipment that fits your shop."],
];

function Logo() {
  return <Link href="/" className="flex items-center gap-2" aria-label="DukaOS home"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary text-sm font-bold text-white shadow-[0_8px_20px_rgba(15,123,108,0.2)]">D</span><span className="text-lg font-bold tracking-[0.16em]">DUKA<span className="text-primary">OS</span></span></Link>;
}

function ProductPreview() {
  return (
    <div className="landing-preview relative overflow-hidden rounded-2xl border border-white/70 bg-white p-3 shadow-[0_28px_80px_rgba(18,57,51,0.2)] sm:p-5">
      <div className="flex items-center justify-between border-b border-border pb-3"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-md bg-primary text-[10px] font-bold text-white">D</span><span className="text-xs font-bold tracking-[0.12em]">DUKAOS</span></div><span className="rounded-full bg-success-tint px-2.5 py-1 text-[10px] font-semibold text-success">Live workspace</span></div>
      <div className="grid gap-3 pt-4 sm:grid-cols-[0.78fr_1.22fr]">
        <div className="hidden space-y-2 rounded-lg bg-[#f4f7f6] p-3 sm:block"><p className="mb-4 text-[9px] font-bold uppercase tracking-[0.16em] text-muted-foreground">Workspace</p>{["Overview", "Point of sale", "Inventory", "Purchases", "Customers"].map((item, index) => <div key={item} className={`rounded-md px-2.5 py-2 text-[10px] font-medium ${index === 0 ? "bg-primary text-white" : "text-muted-foreground"}`}>{item}</div>)}</div>
        <div className="space-y-3"><div><p className="text-[10px] text-muted-foreground">Good morning, your business is moving</p><p className="mt-1 text-lg font-semibold tracking-tight">Today at a glance</p></div><div className="grid grid-cols-2 gap-2"><div className="rounded-lg border border-primary/15 bg-primary-tint p-3"><p className="text-[9px] text-primary/70">Sales today</p><p className="mt-1 font-tabular text-sm font-semibold text-primary">KES 248,500</p><p className="mt-1 text-[9px] text-success">+12.8% this week</p></div><div className="rounded-lg border border-border bg-[#fbfcfc] p-3"><p className="text-[9px] text-muted-foreground">Stock items</p><p className="mt-1 font-tabular text-sm font-semibold">1,284</p><p className="mt-1 text-[9px] text-warning">18 need attention</p></div></div><div className="rounded-lg border border-border p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold">Sales activity</p><p className="text-[9px] text-muted-foreground">This week</p></div><div className="mt-4 flex h-20 items-end gap-2 px-1">{[38, 56, 46, 70, 58, 82, 66].map((height, index) => <span key={index} className={`w-full rounded-t-sm ${index === 5 ? "bg-primary" : "bg-primary/20"}`} style={{ height: `${height}%` }} />)}</div><div className="mt-2 flex justify-between text-[8px] text-muted-foreground"><span>Mon</span><span>Wed</span><span>Fri</span><span>Sun</span></div></div></div>
      </div>
    </div>
  );
}

export function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);

  return <main className="landing-page overflow-hidden bg-[#f8faf9] text-foreground">
    <header className="sticky top-0 z-50 border-b border-[#dce8e3]/80 bg-[#f8faf9]/90 backdrop-blur-md"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><Logo /><nav className="hidden items-center gap-7 text-sm text-muted-foreground lg:flex"><a href="#features" className="hover:text-foreground">Features</a><a href="#how-it-works" className="hover:text-foreground">How it works</a><a href="#industries" className="hover:text-foreground">Who it is for</a><a href="#pricing" className="hover:text-foreground">Pricing</a></nav><div className="hidden items-center gap-3 lg:flex"><Link href="/login" className="px-3 py-2 text-sm font-medium text-foreground hover:text-primary">Log in</Link><Link href="/register" className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-white shadow-[0_8px_18px_rgba(15,123,108,0.18)] hover:bg-primary-hover">Get started <ArrowRight size={15} /></Link></div><button type="button" onClick={() => setMenuOpen((open) => !open)} className="grid h-10 w-10 place-items-center rounded-md border border-border bg-white lg:hidden" aria-label={menuOpen ? "Close menu" : "Open menu"}>{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></div>{menuOpen && <div className="border-t border-border bg-white px-5 py-4 lg:hidden"><nav className="flex flex-col gap-1 text-sm"><a href="#features" onClick={closeMenu} className="rounded-md px-3 py-3">Features</a><a href="#how-it-works" onClick={closeMenu} className="rounded-md px-3 py-3">How it works</a><a href="#industries" onClick={closeMenu} className="rounded-md px-3 py-3">Who it is for</a><a href="#pricing" onClick={closeMenu} className="rounded-md px-3 py-3">Pricing</a><Link href="/login" onClick={closeMenu} className="mt-2 rounded-md px-3 py-3 font-medium text-primary">Log in</Link><Link href="/register" onClick={closeMenu} className="mt-1 inline-flex items-center justify-center gap-2 rounded-md bg-primary px-4 py-3 font-semibold text-white">Get started <ArrowRight size={15} /></Link></nav></div>}</header>

    <section className="relative"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_78%_12%,rgba(141,224,193,0.22),transparent_28%),linear-gradient(120deg,#f8faf9_0%,#eef8f3_60%,#e5f3ee_100%)]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-16 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:gap-16 lg:px-10 lg:pb-24"><div className="max-w-xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-white/70 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[0.16em] text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary" /> Built for growing businesses</div><h1 className="max-w-xl text-5xl font-semibold leading-[0.98] tracking-[-0.03em] sm:text-6xl lg:text-[4.5rem]">Run your business.<br /><span className="text-primary">Know your numbers.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-muted-foreground sm:text-lg">DukaOS brings sales, inventory, purchases, customers, and branches into one clear workspace for modern Kenyan businesses.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-5 py-3.5 text-sm font-semibold text-white shadow-[0_12px_24px_rgba(15,123,108,0.2)] hover:bg-primary-hover">Start your workspace <ArrowRight size={17} /></Link><a href="#features" className="inline-flex items-center justify-center gap-2 rounded-md border border-border-strong bg-white/75 px-5 py-3.5 text-sm font-semibold text-foreground hover:border-primary hover:text-primary">Explore DukaOS</a></div><p className="mt-5 text-xs text-muted-foreground">No complicated setup. No hardware dependency. Built to grow with you.</p></div><ProductPreview /></div></section>

    <section className="border-y border-border bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-9 sm:grid-cols-3 sm:px-8 lg:px-10"><div className="flex items-center gap-3"><ReceiptText className="text-primary" size={22} /><div><p className="text-sm font-semibold">Sell with confidence</p><p className="text-xs text-muted-foreground">Every transaction accounted for</p></div></div><div className="flex items-center gap-3"><WalletCards className="text-primary" size={22} /><div><p className="text-sm font-semibold">Know what is owed</p><p className="text-xs text-muted-foreground">Customer credit and supplier balances</p></div></div><div className="flex items-center gap-3"><ShieldCheck className="text-primary" size={22} /><div><p className="text-sm font-semibold">Keep control</p><p className="text-xs text-muted-foreground">Secure roles and isolated workspaces</p></div></div></div></section>

    <section id="features" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">One connected system</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Everything your business needs to move forward.</h2><p className="mt-4 text-base leading-7 text-muted-foreground">Replace scattered notebooks and disconnected tools with a single operational picture your whole team can use.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-xl border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <div key={title} className="bg-white p-7 transition-colors hover:bg-[#f1faf6]"><Icon className="text-primary" size={22} /><h3 className="mt-7 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></section>

    <section className="bg-[#103f38] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[0.75fr_1.25fr] lg:items-center lg:px-10 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#8de0c1]">The DukaOS difference</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Everything is connected.</h2><p className="mt-5 max-w-md text-sm leading-7 text-emerald-50/70">A sale updates stock. A purchase updates supplier balances. A customer payment updates credit. DukaOS keeps the story of your business in one place.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/15 bg-white/10 p-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#8de0c1]">Sale</p><p className="mt-3 text-sm">Inventory decreases <span className="text-[#8de0c1]">→</span> revenue recorded <span className="text-[#8de0c1]">→</span> reports updated</p></div><div className="rounded-xl border border-white/15 bg-white/10 p-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#8de0c1]">Purchase</p><p className="mt-3 text-sm">Stock increases <span className="text-[#8de0c1]">→</span> supplier balance updated <span className="text-[#8de0c1]">→</span> cost recorded</p></div></div></div></section>

    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">From sign up to insight</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Simple to start. Powerful every day.</h2></div><div className="mt-12 grid gap-8 md:grid-cols-4">{[["01", "Create your business", "Open your secure DukaOS workspace."], ["02", "Set up your shop", "Add branches, users, products, and opening stock."], ["03", "Start selling", "Process daily sales with a fast, focused POS."], ["04", "Grow with clarity", "Use live information to make better decisions."]].map(([number, title, text]) => <div key={number} className="relative border-t-2 border-primary pt-5"><span className="font-tabular text-xs font-semibold text-primary">{number}</span><h3 className="mt-7 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></section>

    <section id="industries" className="border-y border-border bg-[#eef5f1]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-24"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Made for your kind of business</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">One operating rhythm, many industries.</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">Whether you are serving a neighbourhood or several branches, the essentials stay visible.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["Retail shops", "Move products quickly and keep stock honest."], ["Supermarkets", "Coordinate high-volume sales and replenishment."], ["Pharmacies", "Keep products, customers, and records organised."], ["Beauty and cosmetics", "Manage fast-moving products and repeat customers."], ["Wholesalers", "Track purchasing, stock, and customer accounts."], ["Growing teams", "Give every role the right level of access."]].map(([title, text], index) => <div key={title} className="flex items-start gap-4 rounded-lg border border-border bg-white p-5"><span className="font-tabular text-xs font-semibold text-primary">0{index + 1}</span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div></div>)}</div></div></section>

    <section id="pricing" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Plans that grow with you</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Start with what you need. Scale when you are ready.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Choose a package around the way your business operates. Talk to us for current KES pricing and a fit for your team.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{plans.map((plan) => <div key={plan.name} className={`relative rounded-xl border p-7 ${plan.popular ? "border-primary bg-[#effaf5] shadow-[0_16px_35px_rgba(15,123,108,0.12)]" : "border-border bg-white"}`}>{plan.popular && <span className="absolute right-5 top-5 rounded-full bg-primary px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-white">Most popular</span>}<h3 className="text-xl font-semibold">{plan.name}</h3><p className="mt-2 min-h-10 max-w-[14rem] text-sm leading-5 text-muted-foreground">{plan.label}</p><div className="my-7 border-t border-border" />{plan.features.map((feature) => <p key={feature} className="mb-3 flex gap-2 text-sm"><Check className="mt-0.5 shrink-0 text-primary" size={16} />{feature}</p>)}<Link href="/register" className={`mt-5 inline-flex w-full items-center justify-center gap-2 rounded-md px-4 py-3 text-sm font-semibold ${plan.popular ? "bg-primary text-white hover:bg-primary-hover" : "border border-border-strong hover:border-primary hover:text-primary"}`}>Get started <ArrowRight size={15} /></Link></div>)}</div></section>

    <section className="border-t border-border bg-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:px-10 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Good questions</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Clarity before commitment.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">DukaOS is designed to fit into the way you already work, then make it easier to see what happens next.</p></div><div className="divide-y divide-border border-y border-border">{faqs.map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-semibold">{question}<ChevronDown className="shrink-0 text-primary transition-transform group-open:rotate-180" size={18} /></summary><p className="max-w-2xl pr-8 pt-3 text-sm leading-6 text-muted-foreground">{answer}</p></details>)}</div></div></section>

    <section className="bg-[#dff3e9]"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-5 py-16 sm:px-8 md:flex-row md:items-center lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Your next business day</p><h2 className="mt-3 max-w-xl text-3xl font-semibold tracking-tight sm:text-4xl">Ready to take control of your business?</h2><p className="mt-3 text-sm text-muted-foreground">Create your workspace and start seeing the full picture.</p></div><Link href="/register" className="inline-flex shrink-0 items-center gap-2 rounded-md bg-primary px-5 py-3.5 text-sm font-semibold text-white shadow-[0_10px_20px_rgba(15,123,108,0.18)] hover:bg-primary-hover">Create your account <ArrowRight size={17} /></Link></div></section>

    <footer className="bg-[#103f38] text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-10 sm:px-8 md:flex-row md:items-center md:justify-between lg:px-10"><div><Logo /><p className="mt-3 text-xs text-emerald-50/60">The operating system for growing businesses.</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-xs text-emerald-50/70"><a href="#features" className="hover:text-white">Features</a><a href="#pricing" className="hover:text-white">Pricing</a><a href="#how-it-works" className="hover:text-white">How it works</a><Link href="/login" className="hover:text-white">Log in</Link><Link href="/register" className="hover:text-white">Get started</Link></div><p className="text-xs text-emerald-50/45">&copy; {new Date().getFullYear()} DukaOS</p></div></footer>
  </main>;
}